name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.3.0
  dio: ^5.3.2
  json_serializable: ^6.7.1
  hive: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  mocktail: ^1.0.0
